Algoritmo "Medidas"


Var

  A, B, C, Aq, Atri, Atra : real
  

Inicio

   escreval("Digite a medida A: ")
   leia(A)
   escreval("Digite a medida B: ")
   leia(B)
   escreval("Digite a medida B: ")
   leia(C)

   Aq <- A^2
   Atri <- (A * B)/2
   Atra <- ((A + B) * C)/2

   escreval("AREA DO QUADRADO = ", Aq:8:4)
   escreval("AREA DO TRIANGULO = ", Atri:8:4)
   escreval("AREA DO TRAPEZIO = ", Atra:8:4)
   

Fimalgoritmo